[package]
name = "opengl"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1"
ogl33 = { version = "0.2.0", features = ["debug_error_checks"]}

beryllium = { git = "https://github.com/Lokathor/beryllium.git" }
imagine = "0.0.5"
